In [ ]:
with open("workfile", "r") as f:
    content = f.read()  # This will read the content of the file

# The file is automatically closed after the `with` block
#print(content)

In [ ]:
sed -r 's/[^A-Za-z]+/\n/g' workfile | head

In [ ]:
# Use regex to replace non-alphabetic characters with new lines
import re
from collections import Counter


with open('workfile', 'r') as file:
    text = file.read()

lines = re.sub(r'[^A-Za-z]+', '\n', text)

# Get the first few lines
output_lines = lines.splitlines()[:10]  # Adjust the number as needed

# Print the output
for line in output_lines:
    print(line)




In [ ]:
from collections import Counter
import re

# Leggi il contenuto del file
with open('workfile', 'r') as file:
    text = file.read()

# Rimuovi righe vuote e crea una lista di parole usando regex
words = re.findall(r'\b\w+\b', text)  # Trova tutte le parole

# Conta le parole uniche
word_counts = Counter(words)

# Ordina i risultati in ordine numerico decrescente
sorted_counts = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

# Stampa i risultati
nword=0
for word, count in sorted_counts:
    nword+=1
    print(f"{count} {word}")
print(nword)



In [ ]:
import nltk
text = 'That U.S.A. poster-print costs $12.40...'
pattern = r'''(?x) # set flag to strip out spaces and comments
              (?:[A-Z]\.)+  # abbreviations like U.S.A.
              | \w+(?:-\w+)*  # words with optional internal hyphens
              | \$?\d+(?:\.\d+)?%?  # currency and percentages
              | \.\.\.  # ellipsis
              | [][.,;"'?():-_`]  # separate tokens for punctuation
              '''
nltk.regexp_tokenize(text, pattern)


In [ ]:
#pip install nltk


In [1]:
import numpy as np

In [2]:
x= np.zeros(3)
print(x)

for elem in x:
    print(elem)

[0. 0. 0.]
0.0
0.0
0.0


In [ ]:
for i in range(len(x)):
    print("Position" +str(i)+" = " + str(x[i]))


In [ ]:
x = x+1
print(x)

In [ ]:
y = np.zeros((2,3))
print(y)

In [ ]:
for elem in y:
    print(elem)

In [ ]:
import numpy as np

a2D = np.array([[1, 2], [3, 4]]) a2D
Out[6]: array([[1, 2],
[3, 4]])
a2D = np.array([[1, 2], [3, 4]]) a2D
Out[7]: array([[1, 2],
[3, 4]])

In [ ]:
import numpy as np

a= np.array([1,2,3,4])
a
b= np.array([[1,2],[3,4]])
b



In [ ]:
a = np.array([127, 128, 129], dtype=np.int8)
a

In [ ]:
a= np.arange(10)
print(a)
b= np.arange(2, 10, dtype=float)
print(b)
c= np.arange(2, 3, 0.1)
print(c)



In [ ]:
a=np.eye(3)
print(a)
print("\n")
b=np.eye(3,5)
print(b)
print("\n")


In [ ]:
a=np.diag([1,2,3])
print(a)
b=np.diag([1,2,3],5)
print(b)

In [ ]:
np.zeros((2,5,4))

In [ ]:
from numpy.random import default_rng

default_rng(42).random((2,3))

In [ ]:
np.indices((3,3))

In [ ]:
a=np.arange(10)
print(a)
b=a[:2]
print(b)
b+=1
print(b)

In [5]:
a=np.array([1,2,3])
print(a)
a=np.array([[1,2,3],[4,5,6]])
print(a)
a=np.arange(10)
print(a)
a=np.arange(2,10, dtype=float)
print(a)
a=np.arange(2,3,0.1)
print(a)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [8]:
a=np.eye(3)
print(a)

a=np.eye(5,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
a=np.diag([5,3,4,5])
np.diag([5,3,4,6],1)
print(a, "\n")
a=np.array=([[1,2],[3,4]])
print(a)
print(np.diag(a))

[[5 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]] 

[[1, 2], [3, 4]]
[1 4]


In [29]:
np.zeros((2,3))
np.zeros((2,1,3,2))



array([[[[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [11]:
from numpy.random import default_rng as df

df(42).random((2,3))


array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [12]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [19]:
a= np.arange(8)
print(a)
b=a[:2]
print(b)
b+=1
print(a)
print(b)

[0 1 2 3 4 5 6 7]
[0 1]
[1 2 2 3 4 5 6 7]
[1 2]


In [23]:
a= np.arange(8)
print(a)
b=a[:2].copy()
print(b)
b+=1
print(a)
print(b)

[0 1 2 3 4 5 6 7]
[0 1]
[0 1 2 3 4 5 6 7]
[1 2]


In [30]:
x=np.arange(10)
print(x)
x.shape=(2,5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
x[1,3]

8

In [36]:
x[0][2]

2

In [45]:
a=np.arange(20)
b=a[2:17:3]
print(b)
print(type(b))
print(a)
b+=20
print(a)

[ 2  5  8 11 14]
<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1 22  3  4 25  6  7 28  9 10 31 12 13 34 15 16 17 18 19]


In [57]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x)
x.shape
x[1:2]

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


array([[[4],
        [5],
        [6]]])

In [62]:
x = np.array([[[1, 2], [3, 4], [5, 6]], 
              [[7, 8], [9, 10], [11, 12]]])
x.shape

x[1:2]

array([[[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [65]:
x[..., 0]

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [66]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [71]:
x[~np.isnan(x)]

x= np.array([1.,-1,-2.,3])
print(x)

[ 1. -1. -2.  3.]


In [72]:
x[x<0]+=20
print(x)

[ 1. 19. 18.  3.]


In [76]:

x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(x)
# Creiamo un array booleano basato su una condizione
boolean_mask = x > 5  # Restituisce un array booleano
print(boolean_mask)
print(x[boolean_mask])


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[False False]
  [False False]]

 [[False  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]
[ 6  7  8  9 10 11 12]


In [78]:
import numpy as np

# Creiamo un array 3D
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Creiamo un array booleano basato su una condizione
boolean_mask = x > 5  # Restituisce un array booleano

# Usare l'indice del piano (1 per il secondo piano)
# E filtrare solo gli elementi del piano 1 usando la maschera
filtered_values = x[1][boolean_mask[1]]  # Indice 1 per il secondo piano
print(filtered_values)  # Mostra i risultati filtrati


[6 7 8]


In [97]:
x= np.arange(35).reshape(5,7)
print(x, "\n")
b= x>20
print(b)
print("\n")
a=b[:,5]
print(a)
x[a]

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]] 

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


[False False False  True  True]


array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [98]:
import numpy as np

array = np.random.rand(10)
array

array([0.76414575, 0.8548338 , 0.94826524, 0.69659476, 0.03871039,
       0.60072779, 0.41682603, 0.0708833 , 0.98761994, 0.69337068])

In [110]:
array1=np.random.randint(10, size=5)
print(array1)
array2=np.random.randint(10, size=5)
print(array2, "\n")
result= array1+array2
print(result, "\n")
result= array1*array2
print(result)

print(np.max(array1))



[7 3 7 1 2]
[4 1 9 5 9] 

[11  4 16  6 11] 

[28  3 63  5 18]
7


In [111]:
a=np.random.randint(0,10,(3,3))
print(a)

[[8 2 2]
 [1 9 5]
 [0 8 3]]


In [116]:
a=np.random.randint(0,2, (3,3))
b=np.random.randint(0,10,(3,3))
print(a)
print(b)
print(a*b)

[[1 1 1]
 [1 0 1]
 [0 1 0]]
[[7 1 8]
 [8 1 1]
 [2 3 4]]
[[7 1 8]
 [8 0 1]
 [0 3 0]]


In [135]:
arr= np.array([1,2,3])

for x in arr:
    print(x)

arr= np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

for x in arr:
    for y in x:
        print(y, end=",")

print('\n')

arr= np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
print(arr,"\n")
for x in arr:
    print(x, "stop")

for x in np.nditer(arr):
    print(x)


1
2
3
[1 2 3]
[4 5 6]
1,2,3,4,5,6,

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[1 2 3]
 [4 5 6]] stop
[[ 7  8  9]
 [10 11 12]] stop
1
2
3
4
5
6
7
8
9
10
11
12


In [131]:
for x in arr:
    for y in x:
        for z in y:
            print(z, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [136]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [137]:
for x in np.nditer(arr[:,::2]):
    print(x)

1
2
5
6


In [141]:
arr = np.array([1,2,3,4,5,6,7])
arr[2:5]

array([3, 4, 5])

In [145]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

arr[::2]

array([10, 20, 30, 40])

In [154]:
arr = np.array([-1, 10, 1,15,0])
arr
newarr=arr.astype(bool)

newarr

array([ True,  True,  True,  True, False])

Errore: Immagine non trovata o formato non supportato.
